### ISSUE TITLE
what is the coordinate system?

### ISSUE THREAD

**Issue by small-zeng** [theNded/torch-ash#26]
Is the coordinate system from OpenCV or Blender?

**Comment by small-zeng** [comment]
I use own dataset, it occur
`stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
unordered_base::try_insert : Associated bucket and excess list full
unordered_base::try_insert : Associated bucket and excess list full
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0
stdgpu::vector::size : Size out of bounds: -65 not in [0, 12182]. Clamping to 0`
I use opencv coordinate system

**Comment by theNded** [comment]
It is using OpenCV system. Looks like an out-of-bound issue with too varying depth via #23

**Comment by small-zeng** [comment]
> It is using OpenCV system. Looks like an out-of-bound issue with too varying depth via #23

Thank you
