### ISSUE TITLE
RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by small-zeng** [theNded/torch-ash#27]
when I use my data, the problem occur

`CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=3 python demo/train_scene_recon.py --path dataset/l435_scan1/samples --voxel_size 0.015 --depth_type sensor
dataset/l435_scan1/samples image png
dataset/l435_scan1/samples image jpg
dataset/l435_scan1/samples depth png
dataset/l435_scan1/samples omni_normal npy
Loading frame-000238.color.npy: 100%|███████████████████████████████████████████████████████████████████████████████| 239/239 [00:02<00:00, 81.56it/s]
Generating rays for image 238: 100%|████████████████████████████████████████████████████████████████████████████████| 239/239 [00:04<00:00, 55.52it/s]
Transforming normals for image 238: 100%|██████████████████████████████████████████████████████████████████████████| 239/239 [00:01<00:00, 150.08it/s]
voxel_size=0.015
Fuse frame 0:   0%|                                                                                                           | 0/183 [00:00<?, ?it/s]/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/ash/core.py:145: UserWarning: keys are not int32, conversion might reduce precision.
  warnings.warn("keys are not int32, conversion might reduce precision.")
Fuse frame 182: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 183/183 [00:03<00:00, 46.14it/s]
after pruning: 5667
hash map size after pruning: 5667
loss: 0.2058,rgb: 0.0671,normal_l1: 0.3065,normal_cos: 0.5428,depth: 1470074.7500,eikonal_ray: 0.3921:   2%|▏     | 498/20001 [00:24<14:36, 22.25it/s][Open3D WARNING] Write Ply clamped color value to valid range
/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/ash/core.py:179: UserWarning: empty keys
  warnings.warn("empty keys")
loss: 0.2058,rgb: 0.0671,normal_l1: 0.3065,normal_cos: 0.5428,depth: 1470074.7500,eikonal_ray: 0.3921:   2%|▏     | 500/20001 [00:24<15:56, 20.40it/s]
Traceback (most recent call last):
  File "demo/train_scene_recon.py", line 372, in <module>
    result = model(rays_o, rays_d, ray_norms, near=0.0, far=4.0)
  File "/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "demo/train_scene_recon.py", line 113, in forward
    sigmas = self.sdf_to_sigma(sdfs) * masks.float()
  File "/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "demo/train_scene_recon.py", line 31, in forward
    beta = self.min_beta + torch.abs(self.beta)
RuntimeError: CUDA error: invalid configuration argument`

**Comment by theNded** [comment]
It happens when no points are valid in the viewing frustum, probably caused by #23. Could use some boundary checks in error handling.

Also, if possible, please try to post your questions in a consistent thread. One thread per issue is not easy to track since they are probably related. We can open new threads when we confirm the source.

**Comment by small-zeng** [comment]
Sorry， I will do this lately
